# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest1():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.driver.implicitly_wait(10)
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_test1(self):
        self.driver.get("https://comfy.ua/ua/")
        self.driver.set_window_size(1331, 768)

        # Увеличено время ожидания
        WebDriverWait(self.driver, 30).until(EC.visibility_of_element_located((By.CSS_SELECTOR, ".slick-slide:nth-child(6) .str-ban-dsk__carousel-item-img")))

        element = self.driver.find_element(By.CSS_SELECTOR, ".slick-slide:nth-child(6) .str-ban-dsk__carousel-item-img")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()

        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()

        # Увеличено время ожидания
        WebDriverWait(self.driver, 30).until(EC.visibility_of_element_located((By.CSS_SELECTOR, ".header-bottom-profile__link > span")))

        self.driver.find_element(By.CSS_SELECTOR, ".header-bottom-profile__link > span").click()

        # Увеличено время ожидания
        WebDriverWait(self.driver, 30).until(EC.visibility_of_element_located((By.ID, "c-1252")))

        self.driver.find_element(By.ID, "c-1252").click()
        self.driver.find_element(By.ID, "c-1252").send_keys("+38(068)-220-01-22")
        self.driver.find_element(By.CSS_SELECTOR, ".cmf-button-primary__text").click()
        self.driver.find_element(By.CSS_SELECTOR, ".desktop > div:nth-child(1)").click()
        self.driver.find_element(By.CSS_SELECTOR, ".auth-desktop__close").click()

test = TestTest1()
test.setup_method(1)
test.test_test1()
test.teardown_method(1)
