# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUntitled():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_untitled(self):
    self.driver.get("https://comfy.ua/ua/")
    self.driver.set_window_size(1366, 733)
    element = self.driver.find_element(By.LINK_TEXT, "Увійти")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".header-bottom-profile__link > span").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".header-bottom-profile__link > span")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.ID, "c-1249").click()
    self.driver.find_element(By.ID, "c-4391").send_keys("+38(098)-753-13-22")
    self.driver.find_element(By.CSS_SELECTOR, ".cmf-button-primary").click()
    self.driver.find_element(By.CSS_SELECTOR, ".auth-desktop__close").click()
    self.driver.close()
  
test = TestUntitled()
test.setup_method(1)
test.test_untitled()
test.teardown_method(1)
